### ISSUE TITLE
Help please, I spent day trying to solve this issue"'numpy.float64' object does not support item assignment

### ISSUE THREAD

**Issue by manserkm** [hectornieto/pyTSEB#22]
%xmode Verbose
import numpy as np
import matplotlib.pyplot as plt 
from scipy.integrate import odeint 
from scipy.optimize import fsolve

M0=0.5   # Nominal liquid holdup in trays

# Data for linearized liquid flow dynamics (does not apply to reboiler and condenser):
tau=0.063   #time constant for liquid dynamics (min)
F0=1;    #Nominal feed rate (kmol/min) 
qF0 = 1  #Nominal fraction of liquid in feed 
zf0=0.5  # Nominal compenent A fraction in th feed.
LNT=3  #Nominal reflux flow

V0B=2.5# Nominal reboiler flow rate 
L0r=L0 + qF0 * F0 #Nominal liquid flow below feed (kmol/min)
lamda=0     #Effect of vapor flow on liquid flow ("K2-effect")
D0=0.5 * F0 # Destillate molar flowrate mole/min
V0=V0B+(1-qF0)*F0
V0r=V0B#Nominal vapor flows - only
def steady_state(X,ns,nf,qf,zf,r):
    M=X[0:ns]
    x=X[ns:2*ns]
    
    Feed=F0    #kmole/min
    
    B0=Feed-D0    
   
         # Bottom product molar flowrate
    alpha=1.5
    y=np.empty(ns)
       
    for i in range(ns):
        y[i]=alpha*x[i]/(1+(alpha-1)*x[i])
        
    # Vapor Flows assuming constant molar flows
    V=np.empty(ns)
    for i in range(nf+1):
        V[i]=V0
    for i in range (nf+1,ns):
        V[i]=V0r
        
    
    #Liquid flows assuming linearized tray hydraulics with time constant tau
    #Also includes coefficient lambda for effect of vapor flow ("K2-effect")
    L=np.empty(ns)
    
    for i in range(1,nf):
        L[i] = L0r + (M[i]-M0)/tau + lamda*(V[i-1]-V0r)
    for i in range(nf+1,ns-1):
        L[i] = L0 + (M[i]-M0)/tau + lamda*(V[i-1]-V0)
    L[ns-1]=LNT
    dMdt=np.zeros(ns)
    dMxdt = np.zeros(ns)
    
    #reboiler 
    dMdt[0]=L[1]-V[0]-B0
    dMxdt[0]=L[1]*x[1]-V[0]*y[0]-B0*x[0]
   
    #rectyfying section
    for i in range (1,nf):
        dMdt[i]=L[i+1]-L[i]+V[i-1]-V[i]
        dMxdt[i]=L[i+1]*x[i+1]-L[i]*x[i]+V[i-1]*y[i-1]-V[i]*y[i]
        
    #Feed stage
    dMdt[nf]=L[nf+1]-L[nf]+V[nf-1]-V[nf]+Feed
    dMxdt[nf]=zf*Feed+L[nf+1]*x[nf+1]-L[nf]*x[nf]+V[nf-1]*y[nf-1]-V[nf]*y[nf]
    
    #rectyfying section
    for i in range(nf+1,ns-1):
        dMdt=L[i+1]-L[i]+V[i-1]-V[i]
        dMxdt[i]=L[i+1]*x[i+1]-L[i]*x[i]+V[i-1]*y[i-1]-V[i]*y[i]
    
    #reboiler
    dMdt[ns-1]=V[ns-2]-L[ns-1]-D0
    dMxdt[ns-1]=V[ns-2]*y[ns-2]-L[ns-1]*x[ns-1]-D0*x[ns-1]
    
    for i in range(0,ns-1):
        dxdt[i]=(dMxdt[i]-x[i]*dMdt[i])/M[i]
    return np.concatenate((dMdt,dxdt))
ns,nf=25,12
X0=np.ones(2*ns)
X0[0:ns]=0.25# the first column is intials values of M ( molar holdup)
X0[ns:2*ns]=0.5 # the second column is initials values of xi ( liquid mole fraction)
X_ss=fsolve(lambda X:steady_state(X,ns,nf,qf=qF0,zf=zf0,r=0.7),X0)

**Comment by manserkm** [comment]
'numpy.float64' object does not support item assignment
Is the issue that im getting

**Comment by hectornieto** [comment]
Sorry, but this is not part of our code
