### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by niuhaoyu16** [hectornieto/pyTSEB#31]
I install everything sucsessfully. When I was trying to load configure file  Config_LocalImage, I got an error like this:
![image](https://user-images.githubusercontent.com/32653950/60145669-96e6f200-977b-11e9-9131-70f74ad2be3e.png)

**Comment by cugbdxw1998** [comment]
I got the same problem 
How to deal with it?

**Comment by hectornieto** [comment]
Plesae share your configurarion files and all information that could be relevat to better track the issue

**Comment by cugbdxw1998** [comment]
Thanks for the answer. 
I could run the exemple ’TSEB_local_image_main.py‘ in terminal.but when I load the configure file in jupyter notebook. I got an error
![image](https://user-images.githubusercontent.com/77142496/147045104-df4f26a1-5fa4-48fe-ba4a-5521a175d14a.png)

**Comment by hectornieto** [comment]
Commit https://github.com/hectornieto/pyTSEB/commit/0bbd0b1e7c7dde1ab827f5eff1d50231a3f239c0 should now fix this error
Thank you for your feedback

**Comment by radosuav** [comment]
Should be fixed with [7845f14](https://github.com/hectornieto/pyTSEB/commit/7845f14fc03d9b676d94c627e052fc13c77f776d). Please reopen if not.
