### ISSUE TITLE
absorption by water vapor (ω) has no expression

### ISSUE THREAD

**Issue by CamsDongw** [hectornieto/pyTSEB#34]
https://github.com/hectornieto/pyTSEB/blob/0a5b70bca6d04008b47e5f33f82a0b841c4eeff7/pyTSEB/net_radiation.py#L409
As the author modified the expression for Eq. 1 in Weiss and Norman (1985), the expression for ω should be presented earlier (occurred in line 421 actually).

**Comment by hectornieto** [comment]
For PAR it is assumed that WV contribution is negligible so w absorption is set by default at 0
https://github.com/hectornieto/pyTSEB/blob/0a5b70bca6d04008b47e5f33f82a0b841c4eeff7/pyTSEB/net_radiation.py#L391
https://github.com/hectornieto/pyTSEB/blob/0a5b70bca6d04008b47e5f33f82a0b841c4eeff7/pyTSEB/net_radiation.py#L408
