### ISSUE TITLE
Is leaf width set to 0.1 m appropriate for winter wheat？

### ISSUE THREAD

**Issue by CamsDongw** [hectornieto/pyTSEB#35]
https://github.com/hectornieto/pyTSEB/blob/5b64d669ebdde4ba426ddd55b04113b9fa3d619f/pyTSEB/TSEB.py#L475
Hi, I need to seek advice from you. For winter wheat, which portion can be treated as leaf width, lw1 or lw2? Please refer to the picture below. And is leaf width set to 0.1 m appropriate for winter wheat?
 Thank you very much.
![ww](https://user-images.githubusercontent.com/46821916/82277621-ee590680-99ba-11ea-8a2f-31840eb04410.jpg)

**Comment by hectornieto** [comment]
leaf_width parameter is actually an effective leaf size, so 0.1m is probably too high for winter wheat, I would say that 0.05m or even 0.01m would be a more adequate value
