### ISSUE TITLE
How to determine the S_dn_dir and S_dn_dif?

### ISSUE THREAD

**Issue by CamsDongw** [hectornieto/pyTSEB#37]
https://github.com/hectornieto/pyTSEB/blob/3899f3d6db55f38bb9952ab8cfe6279a1cd945f5/pyTSEB/net_radiation.py#L616
Hi, author. Thank you for your sharing about the TSEB-PT code. Now we only have sunshine duration data for the sun radiation. Then we can estimate the total shortwave radiation (Rs). In order to obtain the S_dn_dir and S_dn_dif, we want to know whether the following equations are correct:
S_dn_dir = Rs*fvis*dirvis+Rs*fnir*dirnir;
S_dn_dif = Rs*fvis*difvis+Rs*fnir*difnir;
where, fvis, fnir, dirvis, dirnir, difvis, difnir derive from https://github.com/hectornieto/pyTSEB/blob/3899f3d6db55f38bb9952ab8cfe6279a1cd945f5/pyTSEB/net_radiation.py#L65.

**Comment by hectornieto** [comment]
Check lines
https://github.com/hectornieto/pyTSEB/blob/3899f3d6db55f38bb9952ab8cfe6279a1cd945f5/pyTSEB/PyTSEB.py#L545
to 
https://github.com/hectornieto/pyTSEB/blob/3899f3d6db55f38bb9952ab8cfe6279a1cd945f5/pyTSEB/PyTSEB.py#L547
