### ISSUE TITLE
Negative VZA values causing invalid values of clumping factor

### ISSUE THREAD

**Issue by gabrielmini** [hectornieto/pyTSEB#44]
I tested some MODIS Images using the layer `Day_view_angle` from the product MOD11A1.006. I added the offset of -65 following the [product manual](https://lpdaac.usgs.gov/products/mod11a1v006/). On some days the VZA angle is negative at the position of the Eddy Covariance Flux Tower.

Considering equation 3 (image below) from Kustas and Norman (1999, p.15), and the theta angle (&theta;s) is negative, the solution will produce a complex number due to math property when there is exponentiation of a negative number.
![image](https://user-images.githubusercontent.com/12013961/121583911-41a75800-ca07-11eb-85fb-cd0e8ef980ea.png)

I tried to debug the code and I found the function [calc_omega_Kustas](https://github.com/hectornieto/pyTSEB/blob/ccc0640b3ef0e69e618a7a2e50d92ae2205b81dc/pyTSEB/clumping_index.py#L94). The NumPy array `theta` has `float64` as type. When the code is calculating the omega values, NumPy shows a `RuntimeWarning: invalid value encountered in power`.
To avoid this `RuntimeWarning` the array theta needs to be a `np.complex` instead of `np.float64`, and if the type is not a `np.complex` the number will be transformed automatically to `np.nan`. I don't know what effect this can have on pytseb and the following functions if the theta is transformed to `np.complex`

My doubt is if the VZA angle could be in absolute values. If true, I can manipulate the MODIS image transforming negative values into positive ones, but if false, should I consider it as an invalid pixel value?

**Comment by hectornieto** [comment]
Dear Gabriel, yes, you can/should use the absolute value of the VZA,

All the best,
