### ISSUE TITLE
Doubts in the use of albedo (black/white sky) product

### ISSUE THREAD

**Issue by gabrielmini** [hectornieto/pyTSEB#45]
I was studying the Guzinski et al. (2013, p. 2815) and I found this description below indicating the use of the MODIS albedo products:

<img src="https://user-images.githubusercontent.com/12013961/130704205-61337a1d-d621-41d1-943b-aa2541c488d3.png" width=50% height=50%>

Also, I found another use of the same product (MCD43B3) in the Guzinski et al. (2014, p. 5024)
<img src="https://user-images.githubusercontent.com/12013961/130707464-c5929b91-a51d-40fb-a477-018a2c94e1ea.png" width=50% height=50%>

I checked the PyTSEB code and I didn't found any possible inputs for albedo, being a single value or an image. The main class (PyTSEB.PyTSEB) receives a dictionary as input parameters but none of them shows similarity with albedo. Also, I searched in the code and I found 2 points where the string `"albedo"` was found.

1. **The function `calc_spectra_Cambpell`:** This function estimates the canopy spectral beam/diffuse albedo and transmittances using the Radiative Transfer Model from Campbell and Normam (1998) (equations 15.4 to 15.11). In this function, the values of albedo (beam or diffuse) are estimated using the LAI, SZA, leaf reflectance/transmittance, and soil reflectance. The reflectances and transmittances are constant values; the SZA could be estimated using geographic position and the LAI comes from satellite images (e. g. MCD15A3).

https://github.com/hectornieto/pyTSEB/blob/78900b055f2b15fc5f2fbc713d3619899458f21a/pyTSEB/net_radiation.py#L442

2. **The function `pet_asce` :** According to documentation, this function is used to calculate the latent heat flux for well irrigated and cold pixel using ASCE potential ET from a tall crop. There is a hardcoded value of 0.23 assigned to the variable `albedo`, however, this function is never called in the PyTSEB code.

https://github.com/hectornieto/pyTSEB/blob/ccc0640b3ef0e69e618a7a2e50d92ae2205b81dc/pyTSEB/energy_combination_ET.py#L1031

<br />
<br />

My main doubt is if the PyTSEB needs the albedo inputs from satellite observations (like described in the papers) or if the estimation from the function `calc_spectra_Cambpell` is sufficient.

<br />

**Note:** _The product MCD43B3 was discontinued, however, in February (2021), a General Accuracy Statement was available on the site [NASA MODIS-Land](https://modis-land.gsfc.nasa.gov/ValStatus.php?ProductID=MOD43) suggesting the use of the product MCD43<ins>A</ins>3 (Available since the Collection V6). In the same way, this statement shows a recommendation to not use MODIS products prior to Collection V6, especially for research efforts, however, this is for new research, and for the old ones (that used Collection V5) there is no change._

<br />

**Bibliography:**
Guzinski, R., Anderson, M. C., Kustas, W. P., Nieto, H., & Sandholt, I. (2013). Using a thermal-based two source energy balance model with time-differencing to estimate surface energy fluxes with day-night MODIS observations. Hydrology and Earth System Sciences, 17(7), 2809–2825. https://doi.org/10.5194/hess-17-2809-2013

Guzinski, R., Nieto, H., Jensen, R., & Mendiguren, G. (2014). Remotely sensed land-surface energy fluxes at sub-field scale in heterogeneous agricultural landscape and coniferous plantation. Biogeosciences, 11(18), 5021–5046. https://doi.org/10.5194/bg-11-5021-2014

Campbell, G. S., & Norman, J. M. (1998). An Introduction to Environmental Biophysics. Springer New York. https://doi.org/10.1007/978-1-4612-1626-1

**Comment by hectornieto** [comment]
The estimations made by `calc_spectra_Cambpell` or `calc_Sn_cambpell` are enough and indeed is recommended to use instead of a bulk canopy albedo. 

If you still want to use bulk surface albedo (e.g. from MODIS) you can always compute your own net shortwave radiation and feed it into the `TSEB` module:

https://github.com/hectornieto/pyTSEB/blob/50789259161c6ae38854170c61fff4be78fde4b4/pyTSEB/TSEB.py#L462
