### ISSUE TITLE
something wrong with the guide documentation

### ISSUE THREAD

**Issue by hgbzzw** [hectornieto/pyTSEB#48]
The ancillary result doesn't match the guide documentation from the fifth band,  11 and 13 are the same， called “Friction velocity (m s-1)” shown in the picture.
![image](https://user-images.githubusercontent.com/26102249/150083255-0722faf0-8d3d-4ed8-9bc2-c64e4c84197f.png)
Is something wrong with the guide documentation?

**Comment by hectornieto** [comment]
This has just been fixed, thank you for your feedback
