### ISSUE TITLE
Error running TSEB-2T when using TIFF as input for canopy temperature (first band)

### ISSUE THREAD

**Issue by jsbates** [hectornieto/pyTSEB#52]
I am using the most recent version of pyTSEB and I am having a strange issue when using the TSEB-2T version of it. Below is the error I am getting. I have also attached a screen capture. 

gdal version 3.4
python version 3.10.9

`Provide a valid S_dn_24 (Daily shortwave irradiance) value if you want to estimate daily ET
F:/Raw_Data/2021/Selhausen/20210720_ICOS/FLIR/1325_flight/720_FLIR_Removed_modified3_kelvin_resample_crop.tif image not present for parameter T_R1
ERROR: file read T_S
Please type a valid filename or a numeric value for`

I have used several different TIFF files and still get the same error and the files are used successfully with the DTD and default TSEB versions. It runs when I put in a numerical value for the first band and TIFF for second band. If I use a TIFF for first band and numerical value for the second band, same error.

**Comment by hectornieto** [comment]
Please confirm that when using TSEB-2T your input T_R1 image contains two bands with respectively canopy and soil temperatures. Actually there was a typo in the example `Configuration_LocalImage.txt` file:

> If running TSEB_2T the input T_R1 should contain at least 2 bands: [band 1: Canopy temperature, band 2: soil temperature]
