### ISSUE TITLE
from pyTSEB import TSEB Error: Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by frzambra** [hectornieto/pyTSEB#54]
Hi all, 

I'm using senET ([https://www.esa-sen4et.org/](https://www.esa-sen4et.org/)) which uses the `pyTSEB`, but I'm having the error `Segmentation fault (core dumped) `, I cannot figure what can be happening. I'm running in a ubuntu 22.10 64bit machine.

The error it's coming after this line

```python
from pyTSEB import TSEB
Error: Segmentation fault (core dumped) 
```

**Comment by hectornieto** [comment]
Try importing TSEB from a Python command line. But I suspect this is an issue related to SENET so please contact the appropiate forum.
