### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by zhongwangwei** [hectornieto/pyTSEB#55]
Great work. I have a question.  If I run 1*1 degrees on a global scale, how to set up the Standard longitude of the time zone (degrees) for each grid?
Thank you very much for your kindly help.
Best

**Comment by hectornieto** [comment]
Dear Zhongwang

If you are using a global grid it is most likely your input data is
represented by GMT time, so the standard longitude for all pixels should be
0.

All the best

**Comment by zhongwangwei** [comment]
thank you very much.
