### ISSUE TITLE
Notebook GUI does not seem to run pyTSEB in Windows

### ISSUE THREAD

**Issue by alvarezsergiom1** [hectornieto/pyTSEB#60]
Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
ERROR 4: : No such file or directory
ERROR 4: : No such file or directory
ERROR 4: : No such file or directory

and then it does not continue to run TSEB

**Comment by hectornieto** [comment]
These messages are caused when an optional product is not found (e.g. downwelling longwave irradiance), then TSEB computes internally such data and continues to run
